name: lti-ox6q
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/var/www/html
    environment:
      RUN_MIGRATIONS: "1"
      CACHE_DRIVER: file
  frontend:
    platform: linux/amd64 # For compatibility across windows and Mac
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      VITE_API_BASE_URL: http://localhost:8000
volumes:
  frontend_node_modules: